backend:
  name: github
  repo: mateuszk969/one-click-hugo-cms
  branch: master # Branch to update (master by default)
publish_mode: editorial_workflow
media_folder: "assets" # Folder where user uploaded files should go
public_folder: "assets"
media_library:
  name: uploadcare
  config:
    publicKey: 933276a6b9330ff2b78c
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}--{{minute}}--{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: "json"
    extension: "json"
    fields: # The fields for each document, usually in front matter
      - label: "Categories"
        name: "categories"
        widget: "list"
        required: true
        fields:
          - {
              label: "Category",
              name: "category",
              widget: "select",
              options:
                [
                  "Cryptocurrencies",
                  "Markets",
                  "Economy",
                  "Regulations",
                  "Wellness",
                  "Omega Group",
                ],
            }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: true,
        }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        fields:
          - { label: item, name: item, widget: image }